:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

:: copy files from JCDECAUX.wcf.server/bin/Release/* to Release/JCDECAUX.wcf.server
xcopy /s /y /q JCDECAUX.wcf.server\bin\Release\* packaged\JCDECAUX.wcf.server
:: copy files from Routing.wcf.server/bin/Release/* to Release/Routing.wcf.server
xcopy /s /y /q Routing.wcf.server\bin\Release\* packaged\Routing.wcf.server
:: copy files from HeavyClient/target/* to Release/HeavyClient
xcopy /s /y /q HeavyClient\target\*-shaded.jar packaged\HeavyClient

