/*
 * JcDecaux
 *
 * JcDecaux API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing Contract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContractTests
    {
        // TODO uncomment below to declare an instance variable for Contract
        //private Contract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Contract
            //instance = new Contract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Contract
        /// </summary>
        [Test]
        public void ContractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Contract
            //Assert.IsInstanceOfType<Contract> (instance, "variable 'instance' is a Contract");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CommercialName'
        /// </summary>
        [Test]
        public void CommercialNameTest()
        {
            // TODO unit test for the property 'CommercialName'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Cities'
        /// </summary>
        [Test]
        public void CitiesTest()
        {
            // TODO unit test for the property 'Cities'
        }

    }

}
