/*
 * JcDecaux
 *
 * JcDecaux API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing Park
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ParkTests
    {
        // TODO uncomment below to declare an instance variable for Park
        //private Park instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Park
            //instance = new Park();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Park
        /// </summary>
        [Test]
        public void ParkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Park
            //Assert.IsInstanceOfType<Park> (instance, "variable 'instance' is a Park");
        }


        /// <summary>
        /// Test the property 'ContractName'
        /// </summary>
        [Test]
        public void ContractNameTest()
        {
            // TODO unit test for the property 'ContractName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'AccessType'
        /// </summary>
        [Test]
        public void AccessTypeTest()
        {
            // TODO unit test for the property 'AccessType'
        }
        /// <summary>
        /// Test the property 'LockerType'
        /// </summary>
        [Test]
        public void LockerTypeTest()
        {
            // TODO unit test for the property 'LockerType'
        }
        /// <summary>
        /// Test the property 'HasSurveillance'
        /// </summary>
        [Test]
        public void HasSurveillanceTest()
        {
            // TODO unit test for the property 'HasSurveillance'
        }
        /// <summary>
        /// Test the property 'IsFree'
        /// </summary>
        [Test]
        public void IsFreeTest()
        {
            // TODO unit test for the property 'IsFree'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ZipCode'
        /// </summary>
        [Test]
        public void ZipCodeTest()
        {
            // TODO unit test for the property 'ZipCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'IsOffStreet'
        /// </summary>
        [Test]
        public void IsOffStreetTest()
        {
            // TODO unit test for the property 'IsOffStreet'
        }
        /// <summary>
        /// Test the property 'HasElectricSupport'
        /// </summary>
        [Test]
        public void HasElectricSupportTest()
        {
            // TODO unit test for the property 'HasElectricSupport'
        }
        /// <summary>
        /// Test the property 'HasPhysicalReception'
        /// </summary>
        [Test]
        public void HasPhysicalReceptionTest()
        {
            // TODO unit test for the property 'HasPhysicalReception'
        }

    }

}
