/*
 * JcDecaux
 *
 * JcDecaux API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing StationTotalStands
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StationTotalStandsTests
    {
        // TODO uncomment below to declare an instance variable for StationTotalStands
        //private StationTotalStands instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StationTotalStands
            //instance = new StationTotalStands();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StationTotalStands
        /// </summary>
        [Test]
        public void StationTotalStandsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StationTotalStands
            //Assert.IsInstanceOfType<StationTotalStands> (instance, "variable 'instance' is a StationTotalStands");
        }


        /// <summary>
        /// Test the property 'Availabilities'
        /// </summary>
        [Test]
        public void AvailabilitiesTest()
        {
            // TODO unit test for the property 'Availabilities'
        }
        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Test]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }

    }

}
