/*
 * JcDecaux
 *
 * JcDecaux API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing StationTotalStandsAvailabilities
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StationTotalStandsAvailabilitiesTests
    {
        // TODO uncomment below to declare an instance variable for StationTotalStandsAvailabilities
        //private StationTotalStandsAvailabilities instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StationTotalStandsAvailabilities
            //instance = new StationTotalStandsAvailabilities();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StationTotalStandsAvailabilities
        /// </summary>
        [Test]
        public void StationTotalStandsAvailabilitiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StationTotalStandsAvailabilities
            //Assert.IsInstanceOfType<StationTotalStandsAvailabilities> (instance, "variable 'instance' is a StationTotalStandsAvailabilities");
        }


        /// <summary>
        /// Test the property 'Bikes'
        /// </summary>
        [Test]
        public void BikesTest()
        {
            // TODO unit test for the property 'Bikes'
        }
        /// <summary>
        /// Test the property 'Stands'
        /// </summary>
        [Test]
        public void StandsTest()
        {
            // TODO unit test for the property 'Stands'
        }
        /// <summary>
        /// Test the property 'MechanicalBikes'
        /// </summary>
        [Test]
        public void MechanicalBikesTest()
        {
            // TODO unit test for the property 'MechanicalBikes'
        }
        /// <summary>
        /// Test the property 'ElectricalBikes'
        /// </summary>
        [Test]
        public void ElectricalBikesTest()
        {
            // TODO unit test for the property 'ElectricalBikes'
        }
        /// <summary>
        /// Test the property 'ElectricalInternalBatteryBikes'
        /// </summary>
        [Test]
        public void ElectricalInternalBatteryBikesTest()
        {
            // TODO unit test for the property 'ElectricalInternalBatteryBikes'
        }
        /// <summary>
        /// Test the property 'ElectricalRemovableBatteryBikes'
        /// </summary>
        [Test]
        public void ElectricalRemovableBatteryBikesTest()
        {
            // TODO unit test for the property 'ElectricalRemovableBatteryBikes'
        }

    }

}
