/*
 * JcDecaux
 *
 * JcDecaux API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test.Model
{
    /// <summary>
    ///  Class for testing Station
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StationTests
    {
        // TODO uncomment below to declare an instance variable for Station
        //private Station instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Station
            //instance = new Station();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Station
        /// </summary>
        [Test]
        public void StationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Station
            //Assert.IsInstanceOfType<Station> (instance, "variable 'instance' is a Station");
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'ContractName'
        /// </summary>
        [Test]
        public void ContractNameTest()
        {
            // TODO unit test for the property 'ContractName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Banking'
        /// </summary>
        [Test]
        public void BankingTest()
        {
            // TODO unit test for the property 'Banking'
        }
        /// <summary>
        /// Test the property 'Bonus'
        /// </summary>
        [Test]
        public void BonusTest()
        {
            // TODO unit test for the property 'Bonus'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Test]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
        /// <summary>
        /// Test the property 'Connected'
        /// </summary>
        [Test]
        public void ConnectedTest()
        {
            // TODO unit test for the property 'Connected'
        }
        /// <summary>
        /// Test the property 'Overflow'
        /// </summary>
        [Test]
        public void OverflowTest()
        {
            // TODO unit test for the property 'Overflow'
        }
        /// <summary>
        /// Test the property 'Shape'
        /// </summary>
        [Test]
        public void ShapeTest()
        {
            // TODO unit test for the property 'Shape'
        }
        /// <summary>
        /// Test the property 'TotalStands'
        /// </summary>
        [Test]
        public void TotalStandsTest()
        {
            // TODO unit test for the property 'TotalStands'
        }
        /// <summary>
        /// Test the property 'MainStands'
        /// </summary>
        [Test]
        public void MainStandsTest()
        {
            // TODO unit test for the property 'MainStands'
        }
        /// <summary>
        /// Test the property 'OverflowStands'
        /// </summary>
        [Test]
        public void OverflowStandsTest()
        {
            // TODO unit test for the property 'OverflowStands'
        }

    }

}
