//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routing.wcf.library.JcdecauxProxyService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/JCDECAUX.rest.client.Model")]
    public partial class Contract : object
    {
        
        private string[] citiesField;
        
        private string commercial_nameField;
        
        private string country_codeField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] cities
        {
            get
            {
                return this.citiesField;
            }
            set
            {
                this.citiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string commercial_name
        {
            get
            {
                return this.commercial_nameField;
            }
            set
            {
                this.commercial_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string country_code
        {
            get
            {
                return this.country_codeField;
            }
            set
            {
                this.country_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/JCDECAUX.rest.client.Model")]
    public partial class Station : object
    {
        
        private string addressField;
        
        private System.Nullable<int> available_bike_standsField;
        
        private System.Nullable<int> available_bikesField;
        
        private System.Nullable<bool> bankingField;
        
        private System.Nullable<int> bike_standsField;
        
        private System.Nullable<bool> bonusField;
        
        private string contract_nameField;
        
        private System.Nullable<long> last_updateField;
        
        private string nameField;
        
        private System.Nullable<int> numberField;
        
        private Routing.wcf.library.JcdecauxProxyService.StationPosition positionField;
        
        private string statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> available_bike_stands
        {
            get
            {
                return this.available_bike_standsField;
            }
            set
            {
                this.available_bike_standsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> available_bikes
        {
            get
            {
                return this.available_bikesField;
            }
            set
            {
                this.available_bikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> banking
        {
            get
            {
                return this.bankingField;
            }
            set
            {
                this.bankingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> bike_stands
        {
            get
            {
                return this.bike_standsField;
            }
            set
            {
                this.bike_standsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string contract_name
        {
            get
            {
                return this.contract_nameField;
            }
            set
            {
                this.contract_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<long> last_update
        {
            get
            {
                return this.last_updateField;
            }
            set
            {
                this.last_updateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Routing.wcf.library.JcdecauxProxyService.StationPosition position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationPosition", Namespace="http://schemas.datacontract.org/2004/07/JCDECAUX.rest.client.Model")]
    public partial class StationPosition : object
    {
        
        private System.Nullable<decimal> latField;
        
        private System.Nullable<decimal> lngField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> lng
        {
            get
            {
                return this.lngField;
            }
            set
            {
                this.lngField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Park", Namespace="http://schemas.datacontract.org/2004/07/JCDECAUX.rest.client.Model")]
    public partial class Park : object
    {
        
        private string accessTypeField;
        
        private string addressField;
        
        private string cityField;
        
        private string contractNameField;
        
        private System.Nullable<bool> hasElectricSupportField;
        
        private System.Nullable<bool> hasPhysicalReceptionField;
        
        private System.Nullable<bool> hasSurveillanceField;
        
        private System.Nullable<bool> isFreeField;
        
        private System.Nullable<bool> isOffStreetField;
        
        private string lockerTypeField;
        
        private string nameField;
        
        private System.Nullable<int> numberField;
        
        private Routing.wcf.library.JcdecauxProxyService.ParkPosition positionField;
        
        private string statusField;
        
        private string zipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string accessType
        {
            get
            {
                return this.accessTypeField;
            }
            set
            {
                this.accessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string contractName
        {
            get
            {
                return this.contractNameField;
            }
            set
            {
                this.contractNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> hasElectricSupport
        {
            get
            {
                return this.hasElectricSupportField;
            }
            set
            {
                this.hasElectricSupportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> hasPhysicalReception
        {
            get
            {
                return this.hasPhysicalReceptionField;
            }
            set
            {
                this.hasPhysicalReceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> hasSurveillance
        {
            get
            {
                return this.hasSurveillanceField;
            }
            set
            {
                this.hasSurveillanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> isFree
        {
            get
            {
                return this.isFreeField;
            }
            set
            {
                this.isFreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> isOffStreet
        {
            get
            {
                return this.isOffStreetField;
            }
            set
            {
                this.isOffStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lockerType
        {
            get
            {
                return this.lockerTypeField;
            }
            set
            {
                this.lockerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Routing.wcf.library.JcdecauxProxyService.ParkPosition position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParkPosition", Namespace="http://schemas.datacontract.org/2004/07/JCDECAUX.rest.client.Model")]
    public partial class ParkPosition : object
    {
        
        private System.Nullable<decimal> latitudeField;
        
        private System.Nullable<decimal> longitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Routing.wcf.library.JcdecauxProxyService.IJcdecauxProxyService")]
    public interface IJcdecauxProxyService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJcdecauxProxyService/GetContracts", ReplyAction="http://tempuri.org/IJcdecauxProxyService/GetContractsResponse")]
        System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Contract[]> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJcdecauxProxyService/GetStations", ReplyAction="http://tempuri.org/IJcdecauxProxyService/GetStationsResponse")]
        System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Station[]> GetStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJcdecauxProxyService/GetStation", ReplyAction="http://tempuri.org/IJcdecauxProxyService/GetStationResponse")]
        System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Station> GetStationAsync(int stationNumber, string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJcdecauxProxyService/GetParks", ReplyAction="http://tempuri.org/IJcdecauxProxyService/GetParksResponse")]
        System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Park[]> GetParksAsync(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJcdecauxProxyService/GetPark", ReplyAction="http://tempuri.org/IJcdecauxProxyService/GetParkResponse")]
        System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Park> GetParkAsync(int parkNumber, string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IJcdecauxProxyServiceChannel : Routing.wcf.library.JcdecauxProxyService.IJcdecauxProxyService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class JcdecauxProxyServiceClient : System.ServiceModel.ClientBase<Routing.wcf.library.JcdecauxProxyService.IJcdecauxProxyService>, Routing.wcf.library.JcdecauxProxyService.IJcdecauxProxyService
    {
        
        public JcdecauxProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Contract[]> GetContractsAsync()
        {
            return base.Channel.GetContractsAsync();
        }
        
        public System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Station[]> GetStationsAsync()
        {
            return base.Channel.GetStationsAsync();
        }
        
        public System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Station> GetStationAsync(int stationNumber, string contractName)
        {
            return base.Channel.GetStationAsync(stationNumber, contractName);
        }
        
        public System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Park[]> GetParksAsync(string contractName)
        {
            return base.Channel.GetParksAsync(contractName);
        }
        
        public System.Threading.Tasks.Task<Routing.wcf.library.JcdecauxProxyService.Park> GetParkAsync(int parkNumber, string contractName)
        {
            return base.Channel.GetParkAsync(parkNumber, contractName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
