/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlternativeRoutes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlternativeRoutesTests
    {
        // TODO uncomment below to declare an instance variable for AlternativeRoutes
        //private AlternativeRoutes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlternativeRoutes
            //instance = new AlternativeRoutes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlternativeRoutes
        /// </summary>
        [Test]
        public void AlternativeRoutesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlternativeRoutes
            //Assert.IsInstanceOfType<AlternativeRoutes> (instance, "variable 'instance' is a AlternativeRoutes");
        }


        /// <summary>
        /// Test the property 'TargetCount'
        /// </summary>
        [Test]
        public void TargetCountTest()
        {
            // TODO unit test for the property 'TargetCount'
        }
        /// <summary>
        /// Test the property 'WeightFactor'
        /// </summary>
        [Test]
        public void WeightFactorTest()
        {
            // TODO unit test for the property 'WeightFactor'
        }
        /// <summary>
        /// Test the property 'ShareFactor'
        /// </summary>
        [Test]
        public void ShareFactorTest()
        {
            // TODO unit test for the property 'ShareFactor'
        }

    }

}
