/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DirectionsService3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DirectionsService3Tests
    {
        // TODO uncomment below to declare an instance variable for DirectionsService3
        //private DirectionsService3 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DirectionsService3
            //instance = new DirectionsService3();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DirectionsService3
        /// </summary>
        [Test]
        public void DirectionsService3InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DirectionsService3
            //Assert.IsInstanceOfType<DirectionsService3> (instance, "variable 'instance' is a DirectionsService3");
        }


        /// <summary>
        /// Test the property 'Coordinates'
        /// </summary>
        [Test]
        public void CoordinatesTest()
        {
            // TODO unit test for the property 'Coordinates'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Preference'
        /// </summary>
        [Test]
        public void PreferenceTest()
        {
            // TODO unit test for the property 'Preference'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'InstructionsFormat'
        /// </summary>
        [Test]
        public void InstructionsFormatTest()
        {
            // TODO unit test for the property 'InstructionsFormat'
        }
        /// <summary>
        /// Test the property 'RoundaboutExits'
        /// </summary>
        [Test]
        public void RoundaboutExitsTest()
        {
            // TODO unit test for the property 'RoundaboutExits'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Maneuvers'
        /// </summary>
        [Test]
        public void ManeuversTest()
        {
            // TODO unit test for the property 'Maneuvers'
        }
        /// <summary>
        /// Test the property 'Radiuses'
        /// </summary>
        [Test]
        public void RadiusesTest()
        {
            // TODO unit test for the property 'Radiuses'
        }
        /// <summary>
        /// Test the property 'Bearings'
        /// </summary>
        [Test]
        public void BearingsTest()
        {
            // TODO unit test for the property 'Bearings'
        }
        /// <summary>
        /// Test the property 'ContinueStraight'
        /// </summary>
        [Test]
        public void ContinueStraightTest()
        {
            // TODO unit test for the property 'ContinueStraight'
        }
        /// <summary>
        /// Test the property 'Elevation'
        /// </summary>
        [Test]
        public void ElevationTest()
        {
            // TODO unit test for the property 'Elevation'
        }
        /// <summary>
        /// Test the property 'ExtraInfo'
        /// </summary>
        [Test]
        public void ExtraInfoTest()
        {
            // TODO unit test for the property 'ExtraInfo'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'SuppressWarnings'
        /// </summary>
        [Test]
        public void SuppressWarningsTest()
        {
            // TODO unit test for the property 'SuppressWarnings'
        }
        /// <summary>
        /// Test the property 'GeometrySimplify'
        /// </summary>
        [Test]
        public void GeometrySimplifyTest()
        {
            // TODO unit test for the property 'GeometrySimplify'
        }
        /// <summary>
        /// Test the property 'SkipSegments'
        /// </summary>
        [Test]
        public void SkipSegmentsTest()
        {
            // TODO unit test for the property 'SkipSegments'
        }
        /// <summary>
        /// Test the property 'AlternativeRoutes'
        /// </summary>
        [Test]
        public void AlternativeRoutesTest()
        {
            // TODO unit test for the property 'AlternativeRoutes'
        }
        /// <summary>
        /// Test the property 'MaximumSpeed'
        /// </summary>
        [Test]
        public void MaximumSpeedTest()
        {
            // TODO unit test for the property 'MaximumSpeed'
        }
        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Test]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }
        /// <summary>
        /// Test the property 'ScheduleDuration'
        /// </summary>
        [Test]
        public void ScheduleDurationTest()
        {
            // TODO unit test for the property 'ScheduleDuration'
        }
        /// <summary>
        /// Test the property 'ScheduleRows'
        /// </summary>
        [Test]
        public void ScheduleRowsTest()
        {
            // TODO unit test for the property 'ScheduleRows'
        }
        /// <summary>
        /// Test the property 'WalkingTime'
        /// </summary>
        [Test]
        public void WalkingTimeTest()
        {
            // TODO unit test for the property 'WalkingTime'
        }
        /// <summary>
        /// Test the property 'IgnoreTransfers'
        /// </summary>
        [Test]
        public void IgnoreTransfersTest()
        {
            // TODO unit test for the property 'IgnoreTransfers'
        }

    }

}
