/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ElevationLineBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ElevationLineBodyTests
    {
        // TODO uncomment below to declare an instance variable for ElevationLineBody
        //private ElevationLineBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ElevationLineBody
            //instance = new ElevationLineBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ElevationLineBody
        /// </summary>
        [Test]
        public void ElevationLineBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ElevationLineBody
            //Assert.IsInstanceOfType<ElevationLineBody> (instance, "variable 'instance' is a ElevationLineBody");
        }


        /// <summary>
        /// Test the property 'FormatIn'
        /// </summary>
        [Test]
        public void FormatInTest()
        {
            // TODO unit test for the property 'FormatIn'
        }
        /// <summary>
        /// Test the property 'FormatOut'
        /// </summary>
        [Test]
        public void FormatOutTest()
        {
            // TODO unit test for the property 'FormatOut'
        }
        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Test]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }

    }

}
