/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GeoJSONPropertiesObjectOsmTags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeoJSONPropertiesObjectOsmTagsTests
    {
        // TODO uncomment below to declare an instance variable for GeoJSONPropertiesObjectOsmTags
        //private GeoJSONPropertiesObjectOsmTags instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeoJSONPropertiesObjectOsmTags
            //instance = new GeoJSONPropertiesObjectOsmTags();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeoJSONPropertiesObjectOsmTags
        /// </summary>
        [Test]
        public void GeoJSONPropertiesObjectOsmTagsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeoJSONPropertiesObjectOsmTags
            //Assert.IsInstanceOfType<GeoJSONPropertiesObjectOsmTags> (instance, "variable 'instance' is a GeoJSONPropertiesObjectOsmTags");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Test]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'OpeningHours'
        /// </summary>
        [Test]
        public void OpeningHoursTest()
        {
            // TODO unit test for the property 'OpeningHours'
        }
        /// <summary>
        /// Test the property 'Wheelchair'
        /// </summary>
        [Test]
        public void WheelchairTest()
        {
            // TODO unit test for the property 'Wheelchair'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

    }

}
