/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GeoJSONPropertiesObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeoJSONPropertiesObjectTests
    {
        // TODO uncomment below to declare an instance variable for GeoJSONPropertiesObject
        //private GeoJSONPropertiesObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeoJSONPropertiesObject
            //instance = new GeoJSONPropertiesObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeoJSONPropertiesObject
        /// </summary>
        [Test]
        public void GeoJSONPropertiesObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeoJSONPropertiesObject
            //Assert.IsInstanceOfType<GeoJSONPropertiesObject> (instance, "variable 'instance' is a GeoJSONPropertiesObject");
        }


        /// <summary>
        /// Test the property 'OsmId'
        /// </summary>
        [Test]
        public void OsmIdTest()
        {
            // TODO unit test for the property 'OsmId'
        }
        /// <summary>
        /// Test the property 'OsmType'
        /// </summary>
        [Test]
        public void OsmTypeTest()
        {
            // TODO unit test for the property 'OsmType'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'CategoryIds'
        /// </summary>
        [Test]
        public void CategoryIdsTest()
        {
            // TODO unit test for the property 'CategoryIds'
        }
        /// <summary>
        /// Test the property 'OsmTags'
        /// </summary>
        [Test]
        public void OsmTagsTest()
        {
            // TODO unit test for the property 'OsmTags'
        }

    }

}
