/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IsochronesProfileBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IsochronesProfileBodyTests
    {
        // TODO uncomment below to declare an instance variable for IsochronesProfileBody
        //private IsochronesProfileBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IsochronesProfileBody
            //instance = new IsochronesProfileBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IsochronesProfileBody
        /// </summary>
        [Test]
        public void IsochronesProfileBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IsochronesProfileBody
            //Assert.IsInstanceOfType<IsochronesProfileBody> (instance, "variable 'instance' is a IsochronesProfileBody");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Test]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }
        /// <summary>
        /// Test the property 'LocationType'
        /// </summary>
        [Test]
        public void LocationTypeTest()
        {
            // TODO unit test for the property 'LocationType'
        }
        /// <summary>
        /// Test the property 'Range'
        /// </summary>
        [Test]
        public void RangeTest()
        {
            // TODO unit test for the property 'Range'
        }
        /// <summary>
        /// Test the property 'RangeType'
        /// </summary>
        [Test]
        public void RangeTypeTest()
        {
            // TODO unit test for the property 'RangeType'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'AreaUnits'
        /// </summary>
        [Test]
        public void AreaUnitsTest()
        {
            // TODO unit test for the property 'AreaUnits'
        }
        /// <summary>
        /// Test the property 'Intersections'
        /// </summary>
        [Test]
        public void IntersectionsTest()
        {
            // TODO unit test for the property 'Intersections'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Test]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }
        /// <summary>
        /// Test the property 'Smoothing'
        /// </summary>
        [Test]
        public void SmoothingTest()
        {
            // TODO unit test for the property 'Smoothing'
        }

    }

}
