/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JSONIndividualRouteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JSONIndividualRouteResponseTests
    {
        // TODO uncomment below to declare an instance variable for JSONIndividualRouteResponse
        //private JSONIndividualRouteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JSONIndividualRouteResponse
            //instance = new JSONIndividualRouteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JSONIndividualRouteResponse
        /// </summary>
        [Test]
        public void JSONIndividualRouteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JSONIndividualRouteResponse
            //Assert.IsInstanceOfType<JSONIndividualRouteResponse> (instance, "variable 'instance' is a JSONIndividualRouteResponse");
        }


        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Segments'
        /// </summary>
        [Test]
        public void SegmentsTest()
        {
            // TODO unit test for the property 'Segments'
        }
        /// <summary>
        /// Test the property 'Bbox'
        /// </summary>
        [Test]
        public void BboxTest()
        {
            // TODO unit test for the property 'Bbox'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'WayPoints'
        /// </summary>
        [Test]
        public void WayPointsTest()
        {
            // TODO unit test for the property 'WayPoints'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Test]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }
        /// <summary>
        /// Test the property 'Legs'
        /// </summary>
        [Test]
        public void LegsTest()
        {
            // TODO unit test for the property 'Legs'
        }
        /// <summary>
        /// Test the property 'Extras'
        /// </summary>
        [Test]
        public void ExtrasTest()
        {
            // TODO unit test for the property 'Extras'
        }
        /// <summary>
        /// Test the property 'Departure'
        /// </summary>
        [Test]
        public void DepartureTest()
        {
            // TODO unit test for the property 'Departure'
        }
        /// <summary>
        /// Test the property 'Arrival'
        /// </summary>
        [Test]
        public void ArrivalTest()
        {
            // TODO unit test for the property 'Arrival'
        }

    }

}
