/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JsonExportResponseEdges
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JsonExportResponseEdgesTests
    {
        // TODO uncomment below to declare an instance variable for JsonExportResponseEdges
        //private JsonExportResponseEdges instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonExportResponseEdges
            //instance = new JsonExportResponseEdges();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonExportResponseEdges
        /// </summary>
        [Test]
        public void JsonExportResponseEdgesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JsonExportResponseEdges
            //Assert.IsInstanceOfType<JsonExportResponseEdges> (instance, "variable 'instance' is a JsonExportResponseEdges");
        }


        /// <summary>
        /// Test the property 'FromId'
        /// </summary>
        [Test]
        public void FromIdTest()
        {
            // TODO unit test for the property 'FromId'
        }
        /// <summary>
        /// Test the property 'ToId'
        /// </summary>
        [Test]
        public void ToIdTest()
        {
            // TODO unit test for the property 'ToId'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

    }

}
