/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JSONIndividualRouteResponseSegments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JSONIndividualRouteResponseSegmentsTests
    {
        // TODO uncomment below to declare an instance variable for JSONIndividualRouteResponseSegments
        //private JSONIndividualRouteResponseSegments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JSONIndividualRouteResponseSegments
            //instance = new JSONIndividualRouteResponseSegments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JSONIndividualRouteResponseSegments
        /// </summary>
        [Test]
        public void JSONIndividualRouteResponseSegmentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JSONIndividualRouteResponseSegments
            //Assert.IsInstanceOfType<JSONIndividualRouteResponseSegments> (instance, "variable 'instance' is a JSONIndividualRouteResponseSegments");
        }


        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Test]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }
        /// <summary>
        /// Test the property 'Detourfactor'
        /// </summary>
        [Test]
        public void DetourfactorTest()
        {
            // TODO unit test for the property 'Detourfactor'
        }
        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Test]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }
        /// <summary>
        /// Test the property 'Avgspeed'
        /// </summary>
        [Test]
        public void AvgspeedTest()
        {
            // TODO unit test for the property 'Avgspeed'
        }
        /// <summary>
        /// Test the property 'Ascent'
        /// </summary>
        [Test]
        public void AscentTest()
        {
            // TODO unit test for the property 'Ascent'
        }
        /// <summary>
        /// Test the property 'Descent'
        /// </summary>
        [Test]
        public void DescentTest()
        {
            // TODO unit test for the property 'Descent'
        }

    }

}
