/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JsonExportResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JsonExportResponseTests
    {
        // TODO uncomment below to declare an instance variable for JsonExportResponse
        //private JsonExportResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonExportResponse
            //instance = new JsonExportResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonExportResponse
        /// </summary>
        [Test]
        public void JsonExportResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JsonExportResponse
            //Assert.IsInstanceOfType<JsonExportResponse> (instance, "variable 'instance' is a JsonExportResponse");
        }


        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Test]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }
        /// <summary>
        /// Test the property 'Edges'
        /// </summary>
        [Test]
        public void EdgesTest()
        {
            // TODO unit test for the property 'Edges'
        }
        /// <summary>
        /// Test the property 'EdgesExtra'
        /// </summary>
        [Test]
        public void EdgesExtraTest()
        {
            // TODO unit test for the property 'EdgesExtra'
        }
        /// <summary>
        /// Test the property 'Warning'
        /// </summary>
        [Test]
        public void WarningTest()
        {
            // TODO unit test for the property 'Warning'
        }
        /// <summary>
        /// Test the property 'NodesCount'
        /// </summary>
        [Test]
        public void NodesCountTest()
        {
            // TODO unit test for the property 'NodesCount'
        }
        /// <summary>
        /// Test the property 'EdgesCount'
        /// </summary>
        [Test]
        public void EdgesCountTest()
        {
            // TODO unit test for the property 'EdgesCount'
        }

    }

}
