/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JSONLeg
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JSONLegTests
    {
        // TODO uncomment below to declare an instance variable for JSONLeg
        //private JSONLeg instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JSONLeg
            //instance = new JSONLeg();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JSONLeg
        /// </summary>
        [Test]
        public void JSONLegInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JSONLeg
            //Assert.IsInstanceOfType<JSONLeg> (instance, "variable 'instance' is a JSONLeg");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'DepartureLocation'
        /// </summary>
        [Test]
        public void DepartureLocationTest()
        {
            // TODO unit test for the property 'DepartureLocation'
        }
        /// <summary>
        /// Test the property 'TripHeadsign'
        /// </summary>
        [Test]
        public void TripHeadsignTest()
        {
            // TODO unit test for the property 'TripHeadsign'
        }
        /// <summary>
        /// Test the property 'RouteLongName'
        /// </summary>
        [Test]
        public void RouteLongNameTest()
        {
            // TODO unit test for the property 'RouteLongName'
        }
        /// <summary>
        /// Test the property 'RouteShortName'
        /// </summary>
        [Test]
        public void RouteShortNameTest()
        {
            // TODO unit test for the property 'RouteShortName'
        }
        /// <summary>
        /// Test the property 'RouteDesc'
        /// </summary>
        [Test]
        public void RouteDescTest()
        {
            // TODO unit test for the property 'RouteDesc'
        }
        /// <summary>
        /// Test the property 'RouteType'
        /// </summary>
        [Test]
        public void RouteTypeTest()
        {
            // TODO unit test for the property 'RouteType'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Departure'
        /// </summary>
        [Test]
        public void DepartureTest()
        {
            // TODO unit test for the property 'Departure'
        }
        /// <summary>
        /// Test the property 'Arrival'
        /// </summary>
        [Test]
        public void ArrivalTest()
        {
            // TODO unit test for the property 'Arrival'
        }
        /// <summary>
        /// Test the property 'FeedId'
        /// </summary>
        [Test]
        public void FeedIdTest()
        {
            // TODO unit test for the property 'FeedId'
        }
        /// <summary>
        /// Test the property 'TripId'
        /// </summary>
        [Test]
        public void TripIdTest()
        {
            // TODO unit test for the property 'TripId'
        }
        /// <summary>
        /// Test the property 'RouteId'
        /// </summary>
        [Test]
        public void RouteIdTest()
        {
            // TODO unit test for the property 'RouteId'
        }
        /// <summary>
        /// Test the property 'IsInSameVehicleAsPrevious'
        /// </summary>
        [Test]
        public void IsInSameVehicleAsPreviousTest()
        {
            // TODO unit test for the property 'IsInSameVehicleAsPrevious'
        }
        /// <summary>
        /// Test the property 'Geometry'
        /// </summary>
        [Test]
        public void GeometryTest()
        {
            // TODO unit test for the property 'Geometry'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'Stops'
        /// </summary>
        [Test]
        public void StopsTest()
        {
            // TODO unit test for the property 'Stops'
        }

    }

}
