/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JSONStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JSONStepTests
    {
        // TODO uncomment below to declare an instance variable for JSONStep
        //private JSONStep instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JSONStep
            //instance = new JSONStep();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JSONStep
        /// </summary>
        [Test]
        public void JSONStepInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JSONStep
            //Assert.IsInstanceOfType<JSONStep> (instance, "variable 'instance' is a JSONStep");
        }


        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Instruction'
        /// </summary>
        [Test]
        public void InstructionTest()
        {
            // TODO unit test for the property 'Instruction'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ExitNumber'
        /// </summary>
        [Test]
        public void ExitNumberTest()
        {
            // TODO unit test for the property 'ExitNumber'
        }
        /// <summary>
        /// Test the property 'ExitBearings'
        /// </summary>
        [Test]
        public void ExitBearingsTest()
        {
            // TODO unit test for the property 'ExitBearings'
        }
        /// <summary>
        /// Test the property 'WayPoints'
        /// </summary>
        [Test]
        public void WayPointsTest()
        {
            // TODO unit test for the property 'WayPoints'
        }
        /// <summary>
        /// Test the property 'Maneuver'
        /// </summary>
        [Test]
        public void ManeuverTest()
        {
            // TODO unit test for the property 'Maneuver'
        }

    }

}
