/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JSONSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JSONSummaryTests
    {
        // TODO uncomment below to declare an instance variable for JSONSummary
        //private JSONSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JSONSummary
            //instance = new JSONSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JSONSummary
        /// </summary>
        [Test]
        public void JSONSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JSONSummary
            //Assert.IsInstanceOfType<JSONSummary> (instance, "variable 'instance' is a JSONSummary");
        }


        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Ascent'
        /// </summary>
        [Test]
        public void AscentTest()
        {
            // TODO unit test for the property 'Ascent'
        }
        /// <summary>
        /// Test the property 'Descent'
        /// </summary>
        [Test]
        public void DescentTest()
        {
            // TODO unit test for the property 'Descent'
        }
        /// <summary>
        /// Test the property 'Transfers'
        /// </summary>
        [Test]
        public void TransfersTest()
        {
            // TODO unit test for the property 'Transfers'
        }
        /// <summary>
        /// Test the property 'Fare'
        /// </summary>
        [Test]
        public void FareTest()
        {
            // TODO unit test for the property 'Fare'
        }

    }

}
