/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JsonEdgeExtra
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JsonEdgeExtraTests
    {
        // TODO uncomment below to declare an instance variable for JsonEdgeExtra
        //private JsonEdgeExtra instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonEdgeExtra
            //instance = new JsonEdgeExtra();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonEdgeExtra
        /// </summary>
        [Test]
        public void JsonEdgeExtraInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JsonEdgeExtra
            //Assert.IsInstanceOfType<JsonEdgeExtra> (instance, "variable 'instance' is a JsonEdgeExtra");
        }


        /// <summary>
        /// Test the property 'EdgeId'
        /// </summary>
        [Test]
        public void EdgeIdTest()
        {
            // TODO unit test for the property 'EdgeId'
        }
        /// <summary>
        /// Test the property 'Extra'
        /// </summary>
        [Test]
        public void ExtraTest()
        {
            // TODO unit test for the property 'Extra'
        }

    }

}
