/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing JSONPtStop
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JSONPtStopTests
    {
        // TODO uncomment below to declare an instance variable for JSONPtStop
        //private JSONPtStop instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JSONPtStop
            //instance = new JSONPtStop();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JSONPtStop
        /// </summary>
        [Test]
        public void JSONPtStopInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JSONPtStop
            //Assert.IsInstanceOfType<JSONPtStop> (instance, "variable 'instance' is a JSONPtStop");
        }


        /// <summary>
        /// Test the property 'StopId'
        /// </summary>
        [Test]
        public void StopIdTest()
        {
            // TODO unit test for the property 'StopId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'ArrivalTime'
        /// </summary>
        [Test]
        public void ArrivalTimeTest()
        {
            // TODO unit test for the property 'ArrivalTime'
        }
        /// <summary>
        /// Test the property 'PlannedArrivalTime'
        /// </summary>
        [Test]
        public void PlannedArrivalTimeTest()
        {
            // TODO unit test for the property 'PlannedArrivalTime'
        }
        /// <summary>
        /// Test the property 'PredictedArrivalTime'
        /// </summary>
        [Test]
        public void PredictedArrivalTimeTest()
        {
            // TODO unit test for the property 'PredictedArrivalTime'
        }
        /// <summary>
        /// Test the property 'ArrivalCancelled'
        /// </summary>
        [Test]
        public void ArrivalCancelledTest()
        {
            // TODO unit test for the property 'ArrivalCancelled'
        }
        /// <summary>
        /// Test the property 'DepartureTime'
        /// </summary>
        [Test]
        public void DepartureTimeTest()
        {
            // TODO unit test for the property 'DepartureTime'
        }
        /// <summary>
        /// Test the property 'PlannedDepartureTime'
        /// </summary>
        [Test]
        public void PlannedDepartureTimeTest()
        {
            // TODO unit test for the property 'PlannedDepartureTime'
        }
        /// <summary>
        /// Test the property 'PredictedDepartureTime'
        /// </summary>
        [Test]
        public void PredictedDepartureTimeTest()
        {
            // TODO unit test for the property 'PredictedDepartureTime'
        }
        /// <summary>
        /// Test the property 'DepartureCancelled'
        /// </summary>
        [Test]
        public void DepartureCancelledTest()
        {
            // TODO unit test for the property 'DepartureCancelled'
        }

    }

}
