/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MatrixResponseMetadataEngine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatrixResponseMetadataEngineTests
    {
        // TODO uncomment below to declare an instance variable for MatrixResponseMetadataEngine
        //private MatrixResponseMetadataEngine instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatrixResponseMetadataEngine
            //instance = new MatrixResponseMetadataEngine();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatrixResponseMetadataEngine
        /// </summary>
        [Test]
        public void MatrixResponseMetadataEngineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatrixResponseMetadataEngine
            //Assert.IsInstanceOfType<MatrixResponseMetadataEngine> (instance, "variable 'instance' is a MatrixResponseMetadataEngine");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'BuildDate'
        /// </summary>
        [Test]
        public void BuildDateTest()
        {
            // TODO unit test for the property 'BuildDate'
        }
        /// <summary>
        /// Test the property 'GraphDate'
        /// </summary>
        [Test]
        public void GraphDateTest()
        {
            // TODO unit test for the property 'GraphDate'
        }

    }

}
