/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MatrixProfileBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatrixProfileBodyTests
    {
        // TODO uncomment below to declare an instance variable for MatrixProfileBody
        //private MatrixProfileBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatrixProfileBody
            //instance = new MatrixProfileBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatrixProfileBody
        /// </summary>
        [Test]
        public void MatrixProfileBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatrixProfileBody
            //Assert.IsInstanceOfType<MatrixProfileBody> (instance, "variable 'instance' is a MatrixProfileBody");
        }


        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Test]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Sources'
        /// </summary>
        [Test]
        public void SourcesTest()
        {
            // TODO unit test for the property 'Sources'
        }
        /// <summary>
        /// Test the property 'Destinations'
        /// </summary>
        [Test]
        public void DestinationsTest()
        {
            // TODO unit test for the property 'Destinations'
        }
        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Test]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
        /// <summary>
        /// Test the property 'ResolveLocations'
        /// </summary>
        [Test]
        public void ResolveLocationsTest()
        {
            // TODO unit test for the property 'ResolveLocations'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

    }

}
