/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MatrixResponseMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatrixResponseMetadataTests
    {
        // TODO uncomment below to declare an instance variable for MatrixResponseMetadata
        //private MatrixResponseMetadata instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatrixResponseMetadata
            //instance = new MatrixResponseMetadata();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatrixResponseMetadata
        /// </summary>
        [Test]
        public void MatrixResponseMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatrixResponseMetadata
            //Assert.IsInstanceOfType<MatrixResponseMetadata> (instance, "variable 'instance' is a MatrixResponseMetadata");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Attribution'
        /// </summary>
        [Test]
        public void AttributionTest()
        {
            // TODO unit test for the property 'Attribution'
        }
        /// <summary>
        /// Test the property 'OsmFileMd5Hash'
        /// </summary>
        [Test]
        public void OsmFileMd5HashTest()
        {
            // TODO unit test for the property 'OsmFileMd5Hash'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Test]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }
        /// <summary>
        /// Test the property 'SystemMessage'
        /// </summary>
        [Test]
        public void SystemMessageTest()
        {
            // TODO unit test for the property 'SystemMessage'
        }

    }

}
