/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OptimizationJobs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptimizationJobsTests
    {
        // TODO uncomment below to declare an instance variable for OptimizationJobs
        //private OptimizationJobs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptimizationJobs
            //instance = new OptimizationJobs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptimizationJobs
        /// </summary>
        [Test]
        public void OptimizationJobsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptimizationJobs
            //Assert.IsInstanceOfType<OptimizationJobs> (instance, "variable 'instance' is a OptimizationJobs");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'LocationIndex'
        /// </summary>
        [Test]
        public void LocationIndexTest()
        {
            // TODO unit test for the property 'LocationIndex'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Test]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }
        /// <summary>
        /// Test the property 'TimeWindows'
        /// </summary>
        [Test]
        public void TimeWindowsTest()
        {
            // TODO unit test for the property 'TimeWindows'
        }

    }

}
