/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OptimizationBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptimizationBodyTests
    {
        // TODO uncomment below to declare an instance variable for OptimizationBody
        //private OptimizationBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptimizationBody
            //instance = new OptimizationBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptimizationBody
        /// </summary>
        [Test]
        public void OptimizationBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptimizationBody
            //Assert.IsInstanceOfType<OptimizationBody> (instance, "variable 'instance' is a OptimizationBody");
        }


        /// <summary>
        /// Test the property 'Jobs'
        /// </summary>
        [Test]
        public void JobsTest()
        {
            // TODO unit test for the property 'Jobs'
        }
        /// <summary>
        /// Test the property 'Vehicles'
        /// </summary>
        [Test]
        public void VehiclesTest()
        {
            // TODO unit test for the property 'Vehicles'
        }
        /// <summary>
        /// Test the property 'Matrix'
        /// </summary>
        [Test]
        public void MatrixTest()
        {
            // TODO unit test for the property 'Matrix'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
