/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PoisFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PoisFiltersTests
    {
        // TODO uncomment below to declare an instance variable for PoisFilters
        //private PoisFilters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PoisFilters
            //instance = new PoisFilters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PoisFilters
        /// </summary>
        [Test]
        public void PoisFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PoisFilters
            //Assert.IsInstanceOfType<PoisFilters> (instance, "variable 'instance' is a PoisFilters");
        }


        /// <summary>
        /// Test the property 'CategoryGroupIds'
        /// </summary>
        [Test]
        public void CategoryGroupIdsTest()
        {
            // TODO unit test for the property 'CategoryGroupIds'
        }
        /// <summary>
        /// Test the property 'CategoryIds'
        /// </summary>
        [Test]
        public void CategoryIdsTest()
        {
            // TODO unit test for the property 'CategoryIds'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Wheelchair'
        /// </summary>
        [Test]
        public void WheelchairTest()
        {
            // TODO unit test for the property 'Wheelchair'
        }
        /// <summary>
        /// Test the property 'Smoking'
        /// </summary>
        [Test]
        public void SmokingTest()
        {
            // TODO unit test for the property 'Smoking'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }

    }

}
