/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProfileParametersRestrictions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProfileParametersRestrictionsTests
    {
        // TODO uncomment below to declare an instance variable for ProfileParametersRestrictions
        //private ProfileParametersRestrictions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProfileParametersRestrictions
            //instance = new ProfileParametersRestrictions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProfileParametersRestrictions
        /// </summary>
        [Test]
        public void ProfileParametersRestrictionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProfileParametersRestrictions
            //Assert.IsInstanceOfType<ProfileParametersRestrictions> (instance, "variable 'instance' is a ProfileParametersRestrictions");
        }


        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Axleload'
        /// </summary>
        [Test]
        public void AxleloadTest()
        {
            // TODO unit test for the property 'Axleload'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Hazmat'
        /// </summary>
        [Test]
        public void HazmatTest()
        {
            // TODO unit test for the property 'Hazmat'
        }
        /// <summary>
        /// Test the property 'SurfaceType'
        /// </summary>
        [Test]
        public void SurfaceTypeTest()
        {
            // TODO unit test for the property 'SurfaceType'
        }
        /// <summary>
        /// Test the property 'TrackType'
        /// </summary>
        [Test]
        public void TrackTypeTest()
        {
            // TODO unit test for the property 'TrackType'
        }
        /// <summary>
        /// Test the property 'SmoothnessType'
        /// </summary>
        [Test]
        public void SmoothnessTypeTest()
        {
            // TODO unit test for the property 'SmoothnessType'
        }
        /// <summary>
        /// Test the property 'MaximumSlopedKerb'
        /// </summary>
        [Test]
        public void MaximumSlopedKerbTest()
        {
            // TODO unit test for the property 'MaximumSlopedKerb'
        }
        /// <summary>
        /// Test the property 'MaximumIncline'
        /// </summary>
        [Test]
        public void MaximumInclineTest()
        {
            // TODO unit test for the property 'MaximumIncline'
        }
        /// <summary>
        /// Test the property 'MinimumWidth'
        /// </summary>
        [Test]
        public void MinimumWidthTest()
        {
            // TODO unit test for the property 'MinimumWidth'
        }

    }

}
