/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProfileParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProfileParametersTests
    {
        // TODO uncomment below to declare an instance variable for ProfileParameters
        //private ProfileParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProfileParameters
            //instance = new ProfileParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProfileParameters
        /// </summary>
        [Test]
        public void ProfileParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProfileParameters
            //Assert.IsInstanceOfType<ProfileParameters> (instance, "variable 'instance' is a ProfileParameters");
        }


        /// <summary>
        /// Test the property 'Weightings'
        /// </summary>
        [Test]
        public void WeightingsTest()
        {
            // TODO unit test for the property 'Weightings'
        }
        /// <summary>
        /// Test the property 'Restrictions'
        /// </summary>
        [Test]
        public void RestrictionsTest()
        {
            // TODO unit test for the property 'Restrictions'
        }
        /// <summary>
        /// Test the property 'SurfaceQualityKnown'
        /// </summary>
        [Test]
        public void SurfaceQualityKnownTest()
        {
            // TODO unit test for the property 'SurfaceQualityKnown'
        }
        /// <summary>
        /// Test the property 'AllowUnsuitable'
        /// </summary>
        [Test]
        public void AllowUnsuitableTest()
        {
            // TODO unit test for the property 'AllowUnsuitable'
        }

    }

}
