/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RoundTripRouteOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RoundTripRouteOptionsTests
    {
        // TODO uncomment below to declare an instance variable for RoundTripRouteOptions
        //private RoundTripRouteOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RoundTripRouteOptions
            //instance = new RoundTripRouteOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RoundTripRouteOptions
        /// </summary>
        [Test]
        public void RoundTripRouteOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RoundTripRouteOptions
            //Assert.IsInstanceOfType<RoundTripRouteOptions> (instance, "variable 'instance' is a RoundTripRouteOptions");
        }


        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'Seed'
        /// </summary>
        [Test]
        public void SeedTest()
        {
            // TODO unit test for the property 'Seed'
        }

    }

}
