/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RouteOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RouteOptionsTests
    {
        // TODO uncomment below to declare an instance variable for RouteOptions
        //private RouteOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RouteOptions
            //instance = new RouteOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RouteOptions
        /// </summary>
        [Test]
        public void RouteOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RouteOptions
            //Assert.IsInstanceOfType<RouteOptions> (instance, "variable 'instance' is a RouteOptions");
        }


        /// <summary>
        /// Test the property 'AvoidFeatures'
        /// </summary>
        [Test]
        public void AvoidFeaturesTest()
        {
            // TODO unit test for the property 'AvoidFeatures'
        }
        /// <summary>
        /// Test the property 'AvoidBorders'
        /// </summary>
        [Test]
        public void AvoidBordersTest()
        {
            // TODO unit test for the property 'AvoidBorders'
        }
        /// <summary>
        /// Test the property 'AvoidCountries'
        /// </summary>
        [Test]
        public void AvoidCountriesTest()
        {
            // TODO unit test for the property 'AvoidCountries'
        }
        /// <summary>
        /// Test the property 'VehicleType'
        /// </summary>
        [Test]
        public void VehicleTypeTest()
        {
            // TODO unit test for the property 'VehicleType'
        }
        /// <summary>
        /// Test the property 'ProfileParams'
        /// </summary>
        [Test]
        public void ProfileParamsTest()
        {
            // TODO unit test for the property 'ProfileParams'
        }
        /// <summary>
        /// Test the property 'AvoidPolygons'
        /// </summary>
        [Test]
        public void AvoidPolygonsTest()
        {
            // TODO unit test for the property 'AvoidPolygons'
        }
        /// <summary>
        /// Test the property 'RoundTrip'
        /// </summary>
        [Test]
        public void RoundTripTest()
        {
            // TODO unit test for the property 'RoundTrip'
        }

    }

}
