/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V2directionsprofileScheduleDurationUnits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V2directionsprofileScheduleDurationUnitsTests
    {
        // TODO uncomment below to declare an instance variable for V2directionsprofileScheduleDurationUnits
        //private V2directionsprofileScheduleDurationUnits instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V2directionsprofileScheduleDurationUnits
            //instance = new V2directionsprofileScheduleDurationUnits();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V2directionsprofileScheduleDurationUnits
        /// </summary>
        [Test]
        public void V2directionsprofileScheduleDurationUnitsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V2directionsprofileScheduleDurationUnits
            //Assert.IsInstanceOfType<V2directionsprofileScheduleDurationUnits> (instance, "variable 'instance' is a V2directionsprofileScheduleDurationUnits");
        }


        /// <summary>
        /// Test the property 'DateBased'
        /// </summary>
        [Test]
        public void DateBasedTest()
        {
            // TODO unit test for the property 'DateBased'
        }
        /// <summary>
        /// Test the property 'TimeBased'
        /// </summary>
        [Test]
        public void TimeBasedTest()
        {
            // TODO unit test for the property 'TimeBased'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'DurationEstimated'
        /// </summary>
        [Test]
        public void DurationEstimatedTest()
        {
            // TODO unit test for the property 'DurationEstimated'
        }

    }

}
