/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V2directionsprofileWalkingTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V2directionsprofileWalkingTimeTests
    {
        // TODO uncomment below to declare an instance variable for V2directionsprofileWalkingTime
        //private V2directionsprofileWalkingTime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V2directionsprofileWalkingTime
            //instance = new V2directionsprofileWalkingTime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V2directionsprofileWalkingTime
        /// </summary>
        [Test]
        public void V2directionsprofileWalkingTimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V2directionsprofileWalkingTime
            //Assert.IsInstanceOfType<V2directionsprofileWalkingTime> (instance, "variable 'instance' is a V2directionsprofileWalkingTime");
        }


        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Test]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }
        /// <summary>
        /// Test the property 'Nano'
        /// </summary>
        [Test]
        public void NanoTest()
        {
            // TODO unit test for the property 'Nano'
        }
        /// <summary>
        /// Test the property 'Negative'
        /// </summary>
        [Test]
        public void NegativeTest()
        {
            // TODO unit test for the property 'Negative'
        }
        /// <summary>
        /// Test the property 'Zero'
        /// </summary>
        [Test]
        public void ZeroTest()
        {
            // TODO unit test for the property 'Zero'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

    }

}
