/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DirectionsServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DirectionsServiceApiTests
    {
        private DirectionsServiceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DirectionsServiceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DirectionsServiceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DirectionsServiceApi
            //Assert.IsInstanceOfType(typeof(DirectionsServiceApi), instance, "instance is a DirectionsServiceApi");
        }

        /// <summary>
        /// Test GetDefault2
        /// </summary>
        [Test]
        public void GetDefault2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DirectionsService body = null;
            //string profile = null;
            //var response = instance.GetDefault2(body, profile);
            //Assert.IsInstanceOf<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        /// <summary>
        /// Test GetGPXRoute
        /// </summary>
        [Test]
        public void GetGPXRouteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DirectionsService2 body = null;
            //string profile = null;
            //var response = instance.GetGPXRoute(body, profile);
            //Assert.IsInstanceOf<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        /// <summary>
        /// Test GetGeoJsonRoute
        /// </summary>
        [Test]
        public void GetGeoJsonRouteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DirectionsService3 body = null;
            //string profile = null;
            //var response = instance.GetGeoJsonRoute(body, profile);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        /// <summary>
        /// Test GetJsonRoute
        /// </summary>
        [Test]
        public void GetJsonRouteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DirectionsService1 body = null;
            //string profile = null;
            //var response = instance.GetJsonRoute(body, profile);
            //Assert.IsInstanceOf<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        /// <summary>
        /// Test GetSimpleGeoJsonRoute
        /// </summary>
        [Test]
        public void GetSimpleGeoJsonRouteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string profile = null;
            //string start = null;
            //string end = null;
            //var response = instance.GetSimpleGeoJsonRoute(profile, start, end);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
    }

}
