/* 
 * Openrouteservice
 *
 * This is the openrouteservice API documentation for ORS Core-Version 7.1.0. Documentations for [older Core-Versions](https://github.com/GIScience/openrouteservice-docs/releases) can be rendered with the [Swagger-Editor](https://editor-next.swagger.io/).
 *
 * OpenAPI spec version: 7.1.0
 * Contact: support@smartmobility.heigit.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ElevationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ElevationApiTests
    {
        private ElevationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ElevationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ElevationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ElevationApi
            //Assert.IsInstanceOfType(typeof(ElevationApi), instance, "instance is a ElevationApi");
        }

        /// <summary>
        /// Test ElevationLinePost
        /// </summary>
        [Test]
        public void ElevationLinePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ElevationLineBody body = null;
            //string authorization = null;
            //var response = instance.ElevationLinePost(body, authorization);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        /// <summary>
        /// Test ElevationPointGet
        /// </summary>
        [Test]
        public void ElevationPointGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiKey = null;
            //List<decimal?> geometry = null;
            //string formatOut = null;
            //string dataset = null;
            //var response = instance.ElevationPointGet(apiKey, geometry, formatOut, dataset);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        /// <summary>
        /// Test ElevationPointPost
        /// </summary>
        [Test]
        public void ElevationPointPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ElevationPointBody body = null;
            //string authorization = null;
            //var response = instance.ElevationPointPost(body, authorization);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
    }

}
